unique_name: Product Dimension
object_type: dimension
label: Product Dimension
hierarchies:
  - unique_name: Product Dimension Hierarchy
    label: Product Dimension Hierarchy
    levels:
      - unique_name: Product Line
      - unique_name: Product Category
      - unique_name: Product Name
level_attributes:
  - unique_name: Product Name
    label: Product Name
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productkey
    name_column: englishproductname
  - unique_name: Product Line
    label: Product Line
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productline
    name_column: productline
  - unique_name: Product Category
    label: Product Category
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productsubcategoryname
    name_column: productsubcategoryname
type: standard
